"use strict";
exports.__esModule = true;
var imdb_1 = require("./imdb");
var Movie_1 = require("./Movie");
var imdb1 = new imdb_1.imdb([]);
var Avengers1 = new Movie_1.Movie("Avengers", 2006, "USA", "Action");
Avengers1.completeData(["Robert Downey Jr.", "Chris Evans", "Chris Evans"], "Joss Whedon", "Stan Lee", "English", "Movie theaters", true, "Iron Man", "Marvel Studios", "Paramount Pictures");
imdb1.peliculas.push(Avengers1);
var JusticeLeague = new Movie_1.Movie("Justice League: Snyder's Cut", 2021, "USA", "Action");
JusticeLeague.completeData(["Henry Cavill", "Jared Leto", "Ben Affleck"], "Zack Snyder", "Chris Terrio", "English", "Movie theaters", false, "Superman", "DC Films", "HBO Max");
// imdb1.peliculas.push(JusticeLeague);
var CaptainMarvel = new Movie_1.Movie("Captain Marvel", 2019, "USA", "Action");
CaptainMarvel.completeData(["Brie Larson", "Gemma Chan", "Jude Law"], "Anna Boden", "Ryan Fleck", "English", "Movie theaters", true, "Captain Marvel", "Marvel Studios", "Walt Disney Studios Motion Pictures");
// imdb1.peliculas.push(CaptainMarvel);
// imdb1.printAllMovies();
var imdb1JSON = JSON.stringify(imdb1);
console.log(imdb1JSON);
